---
title: "R Notebook"
output: html_notebook
---


## Read in the data
```{r}
library(e1071)
DiamondDataset <- read.csv("diamonds.csv", header=TRUE)
DiamondDataset <- DiamondDataset[1:10000,c(2,6,7,8,9,10,11)]
str(DiamondDataset)
```
## Spliting the data into Test, Train, and Validate
```{r}
library(caret)
set.seed(1234)
spec <- c(train=.6, test=.2, validate=.2)
i <- sample(cut(1:nrow(DiamondDataset), nrow(DiamondDataset)*cumsum(c(0,spec)), labels = names(spec)))

train <- DiamondDataset[i == "train",]
test <- DiamondDataset[i == "test",]
vald <- DiamondDataset[i =="validate",]
```

```{r}
library(tidyverse)
lm1 <- lm(carat ~., data = train)
summary(lm1)
par(mfrow=c(2,2))
plot(lm1)
```
```{r}
pred <- predict(lm1, newdata = test)
cor_lm <- cor(pred, test$carat)
mse_lm <- mean((pred - test$carat)^2)
print(paste("Cor = ", cor_lm))
print(paste("MSE = ", mse_lm))
```
## SVM Linear
```{r}
svm1 <- svm(carat~., data=train, kernel = "linear", cost = 10, scale=TRUE)
summary(svm1)
```

```{r}
pred <- predict(svm1, newdata = test)
cor_svm1 <- cor(pred, test$carat)
mse_svm1 <- mean((pred = test$carat)^2)
print(paste("Cor_svm1 = ", cor_svm1))
print(paste("MSE_svm1 = ", mse_svm1))
```

## Tune
```{r}
tune_svm1 <- tune(svm, carat~., data=vald, kernel="linear", ranges=list(cost=c(0.001, 0.01, 0.1, 1, 5, 10, 100)))
summary(tune_svm1)
```

## Evaluate Best Linear SVM
```{r}
pred <- predict(tune_svm1$best.model, newdata=test)
cor_svm1_tune <- cor(pred, test$carat)
mse_svm1_tune <- mean((pred = test$carat)^2)
print(paste("Cor_svm1_tune = ", cor_svm1_tune))
print(paste("MSE_svm1_tune = ", mse_svm1_tune))
```

## Polynomial Kernel
```{r}
svm2 <- svm(carat~., data=train, kernel="polynomial", cost=10, scale=TRUE)
summary(svm2)
```

```{r}
pred <- predict(svm2, newdata=test)
cor_svm2 <- cor(pred, test$carat)
mse_svm2 <- mean((pred = test$carat)^2)
print(paste("Cor_svm2 = ", cor_svm2))
print(paste("MSE_svm2 = ", mse_svm2))
```

## Radial Kernel
```{r}
svm3 <- svm(carat~., data=train, kernel="radial", cost=10,gamma=1, scale=TRUE)
summary(svm3)
```

```{r}
pred <- predict(svm3, newdata=test)
cor_svm3 <- cor(pred, test$carat)
mse_svm3 <- mean((pred = test$carat)^2)
print(paste("Cor_svm3 = ", cor_svm3))
print(paste("MSE_svm3 = ", mse_svm3))
```

## Tune Hyperperameters

```{r}
set.seed(1234)
tune.out <- tune(svm, carat~., data = vald, kernel="radial", ranges = list(cost=c(0.1,1,10,100,1000), gamma=c(0.5,1,2,3,4)))
summary(tune.out)
```


```{r}
svm4 <- svm(carat~., data = train, kernel = "radial", cost = 100, gamma = 0.5, scale=TRUE)
summary(svm4)
```

```{r}
pred <- predict(svm4, newdata=test)
cor_svm4 <- cor(pred,test$carat)
mse_svm4 <- mean((pred - test$carat)^2)
print(paste("Cor_svm4 = ", cor_svm4))
print(paste("MSE_svm4 = ", mse_svm4))
```

